#Main yaml file
parameters:
  - name: DB_ADMIN_PASSWORD
    type: string
    default: "Tf7avwNM@Ad3YFSI58L"

variables:
  - template: ./templates/variables.yaml

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 
  displayName: Build the .net app and run tests
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 5.0'
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet restore dependencies'
    inputs:
      command: restore
      projects: 'docker/*.sln'
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet build'
    inputs:
      command: 'build'
      projects: 'docker'
      arguments: '--no-restore -o package'
  - script: |
      sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=${{ parameters.DB_ADMIN_PASSWORD }}" -p 1433:1433 --name devops-challenge --hostname devops_challenge -d $(dockerImageSQL)
      sleep 10
      netstat -ntlp
      sqlcmd -S localhost -U sa -P ${{ parameters.DB_ADMIN_PASSWORD }} -Q "select @@version;"
    displayName: Run SQL server and test the connectivity
  - script: |
      dotnet ./package/DevOpsChallenge.SalesApi.dll &
      sleep 10
      curl -v http://localhost:5000/
    displayName: Run the dotnet app and test the connectivity


  
  
    
  